---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  shellcheck:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
    config:
      python_version: 2
      threshold: "C"
  fixme:
    enabled: true
    checks:
      FIXME:
        enabled: false
      TODO:
        enabled: false
      XXX:
        enabled: false
ratings:
  paths:
    - "**.py"
exclude_paths:
  - .ci/vimhdl_tests/*
  - python/vimhdl/_version.py
  - versioneer.py

