---
language: python
python:
  - "2.7"

env:
  global:
    - CACHE=${HOME}/cache
    - GHDL_HOST="http://downloads.sourceforge.net/project/ghdl-updates/Builds"
    - GHDL_URL="${GHDL_HOST}/ghdl-0.33/ghdl-0.33-x86_64-linux.tgz"
  matrix:
    # - VERSION=v7.4      CI_TARGET=vim
    - VERSION=v7.4.1593 CI_TARGET=vim
    - VERSION=v8.0.0001 CI_TARGET=vim
    - VERSION=master    CI_TARGET=vim
    - VERSION=0.1.5     CI_TARGET=neovim
    # - VERSION=master    CI_TARGET=neovim

addons:
  apt:
    packages:
      - autoconf
      - python-dev
      - vim-gnome
      - libtool
      - automake
      - cmake
      - g++
      - pkg-config
      - unzip

before_script:
  - pip install -U pip
  - git submodule update --init --recursive
  - mkdir -p ${CACHE}
  # Vroom's vim mode currently requires a running X server.
  - if [ "${CI_TARGET}" == "vim" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/suoto/hdlcc_ci --recursive --depth 1 ../hdlcc_ci

  - ./dependencies/hdlcc/.ci/scripts/setup_ghdl.sh
  - ./.ci/setup_ghdl.sh
  - if [ "${CI_TARGET}" == "vim" ]; then source ./.ci/setup_vim.sh; fi
  - if [ "${CI_TARGET}" == "neovim" ]; then source ./.ci/setup_nvim.sh; fi

script:
  - set +xe
  - printf '\e[8;50;100t'
  - ./run_tests.sh --log-capture

after_success:
  - rm -f .ci/test_projects/hdl_lib/osvvm_lib/CoveragePkg.vhd
  - export COVERALLS_PARALLEL=true
  - coveralls
  - codecov
after_failure:
  - echo '##########################################################'
  - echo '##########################################################'
  - cat /tmp/vim-hdl.log
  - echo '##########################################################'
  - echo '##########################################################'
  - cat /tmp/hdlcc-stdout.log
  - echo '##########################################################'
  - echo '##########################################################'
  - cat /tmp/hdlcc-stderr.log
  - echo '##########################################################'
  - echo '##########################################################'
  - cat /tmp/hdlcc.log
  - echo '##########################################################'
  - echo '##########################################################'
cache:
  directories:
    - ~/cache/

